### ISSUE TITLE
Version 4.0.1 Linux Compile Error

### ISSUE THREAD

**Issue by jrugia** [LostArtefacts/TRX#1296]
Attempting to compile the latest 4.0.1 source code generates the below error:

> /usr/bin/python3 /home/jojo/TR1X-4.0.1/tools/generate_init -o init.c
Traceback (most recent call last):
  File "/home/jojo/TR1X-4.0.1/tools/generate_init", line 5, in <module>
    from shared.versioning import generate_version
  File "/home/jojo/TR1X-4.0.1/tools/shared/versioning.py", line 4, in <module>
    def get_branch_version(branch: str | None) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
[23/201] Compiling C object TR1X.p/src_game_creature.c.o
ninja: build stopped: subcommand failed.

The error is not present up to 3.1.1 release.  It appears the 'generate_init' file changed a lot since the previous release, unfortunately I lack the knowledge to determine the cause.

Tried several GCC's  8,10,11 same error.  Running Python 3.9.10

**Comment by rr-** [comment]
Please update Python to 3.10, ideally 3.12.

**Comment by jrugia** [comment]
Attempted to run with Python 3.12, still  a no go but the error is different this time:

> [31/201] Generating fake_init with a custom command
FAILED: init.c 
/usr/bin/python3 /home/jojo/TR1X-4.0.1/tools/generate_init -o init.c
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/jojo/TR1X-4.0.1/tools/generate_init", line 37, in <module>
    main()
  File "/home/jojo/TR1X-4.0.1/tools/generate_init", line 31, in main
    update_init_c(output_path=args.output)
  File "/home/jojo/TR1X-4.0.1/tools/generate_init", line 23, in update_init_c
    new_text = get_init_c()
               ^^^^^^^^^^^^
  File "/home/jojo/TR1X-4.0.1/tools/generate_init", line 19, in get_init_c
    return TEMPLATE.format(version=generate_version())
                                   ^^^^^^^^^^^^^^^^^^
  File "/home/jojo/TR1X-4.0.1/tools/shared/versioning.py", line 21, in generate_version
    version = get_branch_version(None)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jojo/TR1X-4.0.1/tools/shared/versioning.py", line 5, in get_branch_version
    return check_output(
           ^^^^^^^^^^^^^
  File "/home/jojo/Py3_12/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jojo/Py3_12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe', '--dirty', '--always', '--abbrev=7', '--tags', '--exclude', 'latest']' returned non-zero exit status 128.
[42/201] Compiling C object TR1X.p/src_game_gameflow.c.o
ninja: build stopped: subcommand failed.

**Comment by rr-** [comment]
How are you running the tool – what's the working directory? Did you download the code, or rather cloned it from GitHub?

**Comment by jrugia** [comment]
Python is self compiled from source. Its' prefix is in my home folder in this case it's "/home/jojo/Py3_12".  Source downloaded from the official website - https://www.python.org/downloads/source/

The 'python3' binary is being ran through /usr/bin/python3 via an update-alternatives config.

Prior to this I've been using Python 3.9 in a similar way for several other programs without issue.

As for the TR1X source I'm using the tarball package from the tags page.
